### ISSUE TITLE
pip install -r requirements-dev.txt fails on AttributeError: 'module' object has no attribute 'lru_cache'

### ISSUE THREAD

**Issue by KrzysztofMadejski** [themoonsheep/project-template#1]
Error:
```
pip install -r requirements-dev.txt
Collecting django~=2.0 (from -r requirements.txt (line 3))
  Using cached Django-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-CT9vPb/django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
```

This might be the result of running on Python 2.x. Are you sure working on Python 3.5 and you have your virtualenv enabled? Run `python --version` to check it.

Use following command to create new virtual env:
```
mkvirtualenv myproject --python=`which python3.5`
```
